
// # JS Package: syntax-tpl-ext.pak.js :: #START# :: @ generated from mod-highlight-syntax/views/js/highlightjs-extra/syntax/tpl/*.js
// Included Files: tpl/*.js #

// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###

// === tpl/django.js

/*
Language: Django
Requires: xml.js
Author: Ivan Sagalaev <maniac@softwaremaniacs.org>
Contributors: Ilya Baryshev <baryshev@gmail.com>
Category: template
*/

// syntax/tpl/django.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('django',
function(hljs) {
	var FILTER = {
		begin: /\|[A-Za-z]+:?/,
		keywords: {
			name:
				'truncatewords removetags linebreaksbr yesno get_digit timesince random striptags ' +
				'filesizeformat escape linebreaks length_is ljust rjust cut urlize fix_ampersands ' +
				'title floatformat capfirst pprint divisibleby add make_list unordered_list urlencode ' +
				'timeuntil urlizetrunc wordcount stringformat linenumbers slice date dictsort ' +
				'dictsortreversed default_if_none pluralize lower join center default ' +
				'truncatewords_html upper length phone2numeric wordwrap time addslashes slugify first ' +
				'escapejs force_escape iriencode last safe safeseq truncatechars localize unlocalize ' +
				'localtime utc timezone'
		},
		contains: [
			hljs.QUOTE_STRING_MODE,
			hljs.APOS_STRING_MODE
		]
	};

	return {
		aliases: ['jinja'],
		case_insensitive: true,
		subLanguage: 'xml',
		contains: [
			hljs.COMMENT(/\{%\s*comment\s*%}/, /\{%\s*endcomment\s*%}/),
			hljs.COMMENT(/\{#/, /#}/),
			{
				className: 'template-tag',
				begin: /\{%/, end: /%}/,
				contains: [
					{
						className: 'name',
						begin: /\w+/,
						keywords: {
							name:
								'comment endcomment load templatetag ifchanged endifchanged if endif firstof for ' +
								'endfor ifnotequal endifnotequal widthratio extends include spaceless ' +
								'endspaceless regroup ifequal endifequal ssi now with cycle url filter ' +
								'endfilter debug block endblock else autoescape endautoescape csrf_token empty elif ' +
								'endwith static trans blocktrans endblocktrans get_static_prefix get_media_prefix ' +
								'plural get_current_language language get_available_languages ' +
								'get_current_language_bidi get_language_info get_language_info_list localize ' +
								'endlocalize localtime endlocaltime timezone endtimezone get_current_timezone ' +
								'verbatim'
						},
						starts: {
							endsWithParent: true,
							keywords: 'in by as',
							contains: [FILTER],
							relevance: 0
						}
					}
				]
			},
			{
				className: 'template-variable',
				begin: /\{\{/, end: /}}/,
				contains: [FILTER]
			}
		]
	};
}
);

// #END

// === tpl/dust.js

/*
Language: Dust
Requires: xml.js
Author: Michael Allen <michael.allen@benefitfocus.com>
Description: Matcher for dust templates.
Category: template
### modified by unixman
*/

// syntax/tpl/dust.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('dust',
function(hljs) {
	var EXPRESSION_KEYWORDS = 'if else'; // eq ne lt lte gt gte select default math sep
	return {
		aliases: ['dst'],
		case_insensitive: true,
		subLanguage: 'xml',
		contains: [
			hljs.COMMENT(/\{\!/, /\!}/), // fix by unixman
			{ // sub-tpl
				className: 'title',
				begin: /\{[\>|\<]/,
				end: /\/?\}/,
				illegal: /\n/
			},
			{ // syntax
				className: 'symbol',
				begin: /\{[\#\/@\:\?\^\+]/,
				end: /\}/,
				illegal: /\n/,
				contains: [
					{
						className: 'symbol',
						begin: /[a-zA-Z\.\-_]+/,
						starts: {
							endsWithParent: true,
							relevance: 0,
							contains: [ hljs.QUOTE_STRING_MODE ]
						},
						keywords: EXPRESSION_KEYWORDS
					}
				],
			},
			{ // variable
				begin: /\{/, end: /\}/,
				illegal: /\n/,
				contains: [
					{
						className: 'keyword',
						begin: /[a-zA-Z0-9_\.]+/,
					//	returnEnd: true
					},
					{
						className: 'regexp',
						end: /(\|[a-z0-9]+)*/,
						starts: {
							endsWithParent: true,
							relevance: 0
						}
					}
				]
			}
		]
	};
}
);

// #END

// === tpl/latte.js

/*
Language: Latte (nette)
Requires: xml.js
Author: Radu Ovidiu I. <iradu@unix-world.org>
Description: Latte is a templating language for PHP (from Nette framework)
Category: template
### created by unixman
*/

// syntax/tpl/latte.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('latte',
function(hljs) {
	var PARAMS = {
		className: 'params',
		begin: '\\(', end: '\\)'
	};

	var FUNCTION_NAMES = 'dump expand cache spaceless include php syntax l r contentType debugbreak block define import layout extends ifset';

	var FUNCTIONS = {
		beginKeywords: FUNCTION_NAMES,
		keywords: {name: FUNCTION_NAMES},
		relevance: 0,
		contains: [
			PARAMS
		]
	};

	var FILTER = {
		begin: /\|[A-Za-z_]+:?/,
		keywords:
			'noescape breaklines bytes capitalize datastream date escapecss escapehtml escapehtmlcomment escapeical escapejs escapeurl escapexml ' +
			'firstupper checkurl implode indent length lower nl2br number padleft padright repeat replace replacere reverse safeurl strip ' +
			'striphtml striptags substr trim truncate upper', // 'webalize' is disabled
		contains: [
			FUNCTIONS
		]
	};

	var TAGS = 	'if else ifset elseifset switch case default ' + // conditions
				'for foreach while continueIf breakIf first last sep ' + // loops
				'var capture'; // variables ('default' is already defined above)


	TAGS = TAGS + ' ' + TAGS.split(' ').map(function(t){return 'end' + t}).join(' ');

	return {
		aliases: ['nettetpl'],
		case_insensitive: true,
		subLanguage: 'xml',
		contains: [
			hljs.COMMENT(/\{\*/, /\*}/),
			{
				className: 'template-variable',
				begin: /\{\$([a-zA-Z0-9])+/, end: /}/,
				contains: ['self', FILTER, FUNCTIONS]
			},
			{
				//className: 'template-tag',
				className: 'symbol',
				begin: /\{\/?/, end: /}/,
				contains: [
					{
						className: 'name',
						begin: /([a-zA-Z0-9])+/,
						keywords: TAGS,
						starts: {
							endsWithParent: true,
							contains: [FILTER, FUNCTIONS],
							relevance: 0
						}
					}
				]
			}
		]
	};
}
);

// #END

// === tpl/twig.js

/*
Language: Twig
Requires: xml.js
Author: Luke Holder <lukemh@gmail.com>
Description: Twig is a templating language for PHP
Category: template
### modified by unixman
*/

// syntax/tpl/twig.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('twig',
function(hljs) {
	var PARAMS = {
		className: 'params',
		begin: '\\(', end: '\\)'
	};

	var FUNCTION_NAMES = 'attribute block constant cycle date dump include ' +
									'max min parent random range source template_from_string';

	var FUNCTIONS = {
		beginKeywords: FUNCTION_NAMES,
		keywords: {name: FUNCTION_NAMES},
		relevance: 0,
		contains: [
			PARAMS
		]
	};

	var FILTER = {
		begin: /\|[A-Za-z_]+:?/,
		keywords:
			'abs batch capitalize convert_encoding date date_modify default ' +
			'escape first format join json_encode keys last length lower ' +
			'merge nl2br number_format raw replace reverse round slice sort split ' +
			'striptags title trim upper url_encode',
		contains: [
			FUNCTIONS
		]
	};

	var TAGS = 'autoescape block do embed extends filter flush for ' +
		'if else import include macro sandbox set spaceless use verbatim'; // fix by unixman ; add: else

	TAGS = TAGS + ' ' + TAGS.split(' ').map(function(t){return 'end' + t}).join(' ');

	return {
		aliases: ['craftcms'],
		case_insensitive: true,
		subLanguage: 'xml',
		contains: [
			hljs.COMMENT(/\{#/, /#}/),
			{
				//className: 'template-tag', // Fix by unixman
				className: 'symbol',
				begin: /\{%/, end: /%}/,
				contains: [
					{
						className: 'name',
						begin: /\w+/,
						keywords: TAGS,
						starts: {
							endsWithParent: true,
							contains: [FILTER, FUNCTIONS],
							relevance: 0
						}
					}
				]
			},
			{
				className: 'template-variable',
				begin: /\{\{/, end: /}}/,
				contains: ['self', FILTER, FUNCTIONS]
			}
		]
	};
}
);

// #END

// ===== [#]

// # JS Package: syntax-tpl-ext.pak.js :: #END#

