
// # JS Package: syntax-lang-ext.pak.js :: #START# :: @ generated from mod-highlight-syntax/views/js/highlightjs-extra/syntax/lang/*.js
// Included Files: lang/*.js #

// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###

// === lang/basic.js

/*
Language: Basic
Author: Raphaël Assénat <raph@raphnet.net>
Description: Based on the BASIC reference from the Tandy 1000 guide
*/

// syntax/lang/basic.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('basic',
function(hljs) {
	return {
		case_insensitive: true,
		illegal: '^\.',
		// Support explicitely typed variables that end with $%! or #.
		lexemes: '[a-zA-Z][a-zA-Z0-9_\$\%\!\#]*',
		keywords: {
				keyword:
					'ABS ASC AND ATN AUTO|0 BEEP BLOAD|10 BSAVE|10 CALL CALLS CDBL CHAIN CHDIR CHR$|10 CINT CIRCLE ' +
					'CLEAR CLOSE CLS COLOR COM COMMON CONT COS CSNG CSRLIN CVD CVI CVS DATA DATE$ ' +
					'DEFDBL DEFINT DEFSNG DEFSTR DEF|0 SEG USR DELETE DIM DRAW EDIT END ENVIRON ENVIRON$ ' +
					'EOF EQV ERASE ERDEV ERDEV$ ERL ERR ERROR EXP FIELD FILES FIX FOR|0 FRE GET GOSUB|10 GOTO ' +
					'HEX$ IF|0 THEN ELSE|0 INKEY$ INP INPUT INPUT# INPUT$ INSTR IMP INT IOCTL IOCTL$ KEY ON ' +
					'OFF LIST KILL LEFT$ LEN LET LINE LLIST LOAD LOC LOCATE LOF LOG LPRINT USING LSET ' +
					'MERGE MID$ MKDIR MKD$ MKI$ MKS$ MOD NAME NEW NEXT NOISE NOT OCT$ ON OR PEN PLAY STRIG OPEN OPTION ' +
					'BASE OUT PAINT PALETTE PCOPY PEEK PMAP POINT POKE POS PRINT PRINT] PSET PRESET ' +
					'PUT RANDOMIZE READ REM RENUM RESET|0 RESTORE RESUME RETURN|0 RIGHT$ RMDIR RND RSET ' +
					'RUN SAVE SCREEN SGN SHELL SIN SOUND SPACE$ SPC SQR STEP STICK STOP STR$ STRING$ SWAP ' +
					'SYSTEM TAB TAN TIME$ TIMER TROFF TRON TO USR VAL VARPTR VARPTR$ VIEW WAIT WHILE ' +
					'WEND WIDTH WINDOW WRITE XOR'
		},
		contains: [
			hljs.QUOTE_STRING_MODE,
			hljs.COMMENT('REM', '$', {relevance: 10}),
			hljs.COMMENT('\'', '$', {relevance: 0}),
			{
				// Match line numbers
				className: 'symbol',
				begin: '^[0-9]+\ ',
				relevance: 10
			},
			{
				// Match typed numeric constants (1000, 12.34!, 1.2e5, 1.5#, 1.2D2)
				className: 'number',
				begin: '\\b([0-9]+[0-9edED\.]*[#\!]?)',
				relevance: 0
			},
			{
				// Match hexadecimal numbers (&Hxxxx)
				className: 'number',
				begin: '(\&[hH][0-9a-fA-F]{1,4})'
			},
			{
				// Match octal numbers (&Oxxxxxx)
				className: 'number',
				begin: '(\&[oO][0-7]{1,6})'
			}
		]
	};
}
);

// #END

// === lang/cs.js

/*
Language: C#
Author: Jason Diamond <jason@diamond.name>
Contributor: Nicolas LLOBERA <nllobera@gmail.com>, Pieter Vantorre <pietervantorre@gmail.com>
Category: common
*/

// syntax/lang/cs.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('cs',
function(hljs) {
	var KEYWORDS = {
		keyword:
			// Normal keywords.
			'abstract as base bool break byte case catch char checked const continue decimal ' +
			'default delegate do double enum event explicit extern finally fixed float ' +
			'for foreach goto if implicit in int interface internal is lock long nameof ' +
			'object operator out override params private protected public readonly ref sbyte ' +
			'sealed short sizeof stackalloc static string struct switch this try typeof ' +
			'uint ulong unchecked unsafe ushort using virtual void volatile while ' +
			// Contextual keywords.
			'add alias ascending async await by descending dynamic equals from get global group into join ' +
			'let on orderby partial remove select set value var where yield',
		literal:
			'null false true'
	};
	var NUMBERS = {
		className: 'number',
		variants: [
			{ begin: '\\b(0b[01\']+)' },
			{ begin: '(-?)\\b([\\d\']+(\\.[\\d\']*)?|\\.[\\d\']+)(u|U|l|L|ul|UL|f|F|b|B)' },
			{ begin: '(-?)(\\b0[xX][a-fA-F0-9\']+|(\\b[\\d\']+(\\.[\\d\']*)?|\\.[\\d\']+)([eE][-+]?[\\d\']+)?)' }
		],
		relevance: 0
	};
	var VERBATIM_STRING = {
		className: 'string',
		begin: '@"', end: '"',
		contains: [{begin: '""'}]
	};
	var VERBATIM_STRING_NO_LF = hljs.inherit(VERBATIM_STRING, {illegal: /\n/});
	var SUBST = {
		className: 'subst',
		begin: '{', end: '}',
		keywords: KEYWORDS
	};
	var SUBST_NO_LF = hljs.inherit(SUBST, {illegal: /\n/});
	var INTERPOLATED_STRING = {
		className: 'string',
		begin: /\$"/, end: '"',
		illegal: /\n/,
		contains: [{begin: '{{'}, {begin: '}}'}, hljs.BACKSLASH_ESCAPE, SUBST_NO_LF]
	};
	var INTERPOLATED_VERBATIM_STRING = {
		className: 'string',
		begin: /\$@"/, end: '"',
		contains: [{begin: '{{'}, {begin: '}}'}, {begin: '""'}, SUBST]
	};
	var INTERPOLATED_VERBATIM_STRING_NO_LF = hljs.inherit(INTERPOLATED_VERBATIM_STRING, {
		illegal: /\n/,
		contains: [{begin: '{{'}, {begin: '}}'}, {begin: '""'}, SUBST_NO_LF]
	});
	SUBST.contains = [
		INTERPOLATED_VERBATIM_STRING,
		INTERPOLATED_STRING,
		VERBATIM_STRING,
		hljs.APOS_STRING_MODE,
		hljs.QUOTE_STRING_MODE,
		NUMBERS,
		hljs.C_BLOCK_COMMENT_MODE
	];
	SUBST_NO_LF.contains = [
		INTERPOLATED_VERBATIM_STRING_NO_LF,
		INTERPOLATED_STRING,
		VERBATIM_STRING_NO_LF,
		hljs.APOS_STRING_MODE,
		hljs.QUOTE_STRING_MODE,
		NUMBERS,
		hljs.inherit(hljs.C_BLOCK_COMMENT_MODE, {illegal: /\n/})
	];
	var STRING = {
		variants: [
			INTERPOLATED_VERBATIM_STRING,
			INTERPOLATED_STRING,
			VERBATIM_STRING,
			hljs.APOS_STRING_MODE,
			hljs.QUOTE_STRING_MODE
		]
	};

	var TYPE_IDENT_RE = hljs.IDENT_RE + '(<' + hljs.IDENT_RE + '(\\s*,\\s*' + hljs.IDENT_RE + ')*>)?(\\[\\])?';

	return {
		aliases: ['csharp'],
		keywords: KEYWORDS,
		illegal: /::/,
		contains: [
			hljs.COMMENT(
				'///',
				'$',
				{
					returnBegin: true,
					contains: [
						{
							className: 'doctag',
							variants: [
								{
									begin: '///', relevance: 0
								},
								{
									begin: '<!--|-->'
								},
								{
									begin: '</?', end: '>'
								}
							]
						}
					]
				}
			),
			hljs.C_LINE_COMMENT_MODE,
			hljs.C_BLOCK_COMMENT_MODE,
			{
				className: 'meta',
				begin: '#', end: '$',
				keywords: {
					'meta-keyword': 'if else elif endif define undef warning error line region endregion pragma checksum'
				}
			},
			STRING,
			NUMBERS,
			{
				beginKeywords: 'class interface', end: /[{;=]/,
				illegal: /[^\s:,]/,
				contains: [
					hljs.TITLE_MODE,
					hljs.C_LINE_COMMENT_MODE,
					hljs.C_BLOCK_COMMENT_MODE
				]
			},
			{
				beginKeywords: 'namespace', end: /[{;=]/,
				illegal: /[^\s:]/,
				contains: [
					hljs.inherit(hljs.TITLE_MODE, {begin: '[a-zA-Z](\\.?\\w)*'}),
					hljs.C_LINE_COMMENT_MODE,
					hljs.C_BLOCK_COMMENT_MODE
				]
			},
			{
				// [Attributes("")]
				className: 'meta',
				begin: '^\\s*\\[', excludeBegin: true, end: '\\]', excludeEnd: true,
				contains: [
					{className: 'meta-string', begin: /"/, end: /"/}
				]
			},
			{
				// Expression keywords prevent 'keyword Name(...)' from being
				// recognized as a function definition
				beginKeywords: 'new return throw await else',
				relevance: 0
			},
			{
				className: 'function',
				begin: '(' + TYPE_IDENT_RE + '\\s+)+' + hljs.IDENT_RE + '\\s*\\(', returnBegin: true,
				end: /\s*[{;=]/, excludeEnd: true,
				keywords: KEYWORDS,
				contains: [
					{
						begin: hljs.IDENT_RE + '\\s*\\(', returnBegin: true,
						contains: [hljs.TITLE_MODE],
						relevance: 0
					},
					{
						className: 'params',
						begin: /\(/, end: /\)/,
						excludeBegin: true,
						excludeEnd: true,
						keywords: KEYWORDS,
						relevance: 0,
						contains: [
							STRING,
							NUMBERS,
							hljs.C_BLOCK_COMMENT_MODE
						]
					},
					hljs.C_LINE_COMMENT_MODE,
					hljs.C_BLOCK_COMMENT_MODE
				]
			}
		]
	};
}
);

// #END

// === lang/d.js

/*
Language: D
Author: Aleksandar Ruzicic <aleksandar@ruzicic.info>
Description: D is a language with C-like syntax and static typing. It pragmatically combines efficiency, control, and modeling power, with safety and programmer productivity.
Version: 1.0a
Date: 2012-04-08
*/

// syntax/lang/d.js
// HighlightJs: v.9.13.1

/**
 * Known issues:
 *
 * - invalid hex string literals will be recognized as a double quoted strings
 *   but 'x' at the beginning of string will not be matched
 *
 * - delimited string literals are not checked for matching end delimiter
 *   (not possible to do with js regexp)
 *
 * - content of token string is colored as a string (i.e. no keyword coloring inside a token string)
 *   also, content of token string is not validated to contain only valid D tokens
 *
 * - special token sequence rule is not strictly following D grammar (anything following #line
 *   up to the end of line is matched as special token sequence)
 */
hljs.registerLanguage('d',
function(hljs) {
	/**
	 * Language keywords
	 *
	 * @type {Object}
	 */
	var D_KEYWORDS = {
		keyword:
			'abstract alias align asm assert auto body break byte case cast catch class ' +
			'const continue debug default delete deprecated do else enum export extern final ' +
			'finally for foreach foreach_reverse|10 goto if immutable import in inout int ' +
			'interface invariant is lazy macro mixin module new nothrow out override package ' +
			'pragma private protected public pure ref return scope shared static struct ' +
			'super switch synchronized template this throw try typedef typeid typeof union ' +
			'unittest version void volatile while with __FILE__ __LINE__ __gshared|10 ' +
			'__thread __traits __DATE__ __EOF__ __TIME__ __TIMESTAMP__ __VENDOR__ __VERSION__',
		built_in:
			'bool cdouble cent cfloat char creal dchar delegate double dstring float function ' +
			'idouble ifloat ireal long real short string ubyte ucent uint ulong ushort wchar ' +
			'wstring',
		literal:
			'false null true'
	};

	/**
	 * Number literal regexps
	 *
	 * @type {String}
	 */
	var decimal_integer_re = '(0|[1-9][\\d_]*)',
		decimal_integer_nosus_re = '(0|[1-9][\\d_]*|\\d[\\d_]*|[\\d_]+?\\d)',
		binary_integer_re = '0[bB][01_]+',
		hexadecimal_digits_re = '([\\da-fA-F][\\da-fA-F_]*|_[\\da-fA-F][\\da-fA-F_]*)',
		hexadecimal_integer_re = '0[xX]' + hexadecimal_digits_re,

		decimal_exponent_re = '([eE][+-]?' + decimal_integer_nosus_re + ')',
		decimal_float_re = '(' + decimal_integer_nosus_re + '(\\.\\d*|' + decimal_exponent_re + ')|' +
								'\\d+\\.' + decimal_integer_nosus_re + decimal_integer_nosus_re + '|' +
								'\\.' + decimal_integer_re + decimal_exponent_re + '?' +
							')',
		hexadecimal_float_re = '(0[xX](' +
									hexadecimal_digits_re + '\\.' + hexadecimal_digits_re + '|'+
									'\\.?' + hexadecimal_digits_re +
								 ')[pP][+-]?' + decimal_integer_nosus_re + ')',

		integer_re = '(' +
			decimal_integer_re + '|' +
			binary_integer_re  + '|' +
			 hexadecimal_integer_re   +
		')',

		float_re = '(' +
			hexadecimal_float_re + '|' +
			decimal_float_re  +
		')';

	/**
	 * Escape sequence supported in D string and character literals
	 *
	 * @type {String}
	 */
	var escape_sequence_re = '\\\\(' +
							'[\'"\\?\\\\abfnrtv]|' +  // common escapes
							'u[\\dA-Fa-f]{4}|' +     // four hex digit unicode codepoint
							'[0-7]{1,3}|' +       // one to three octal digit ascii char code
							'x[\\dA-Fa-f]{2}|' +    // two hex digit ascii char code
							'U[\\dA-Fa-f]{8}' +      // eight hex digit unicode codepoint
							')|' +
							'&[a-zA-Z\\d]{2,};';      // named character entity

	/**
	 * D integer number literals
	 *
	 * @type {Object}
	 */
	var D_INTEGER_MODE = {
		className: 'number',
			begin: '\\b' + integer_re + '(L|u|U|Lu|LU|uL|UL)?',
			relevance: 0
	};

	/**
	 * [D_FLOAT_MODE description]
	 * @type {Object}
	 */
	var D_FLOAT_MODE = {
		className: 'number',
		begin: '\\b(' +
				float_re + '([fF]|L|i|[fF]i|Li)?|' +
				integer_re + '(i|[fF]i|Li)' +
			')',
		relevance: 0
	};

	/**
	 * D character literal
	 *
	 * @type {Object}
	 */
	var D_CHARACTER_MODE = {
		className: 'string',
		begin: '\'(' + escape_sequence_re + '|.)', end: '\'',
		illegal: '.'
	};

	/**
	 * D string escape sequence
	 *
	 * @type {Object}
	 */
	var D_ESCAPE_SEQUENCE = {
		begin: escape_sequence_re,
		relevance: 0
	};

	/**
	 * D double quoted string literal
	 *
	 * @type {Object}
	 */
	var D_STRING_MODE = {
		className: 'string',
		begin: '"',
		contains: [D_ESCAPE_SEQUENCE],
		end: '"[cwd]?'
	};

	/**
	 * D wysiwyg and delimited string literals
	 *
	 * @type {Object}
	 */
	var D_WYSIWYG_DELIMITED_STRING_MODE = {
		className: 'string',
		begin: '[rq]"',
		end: '"[cwd]?',
		relevance: 5
	};

	/**
	 * D alternate wysiwyg string literal
	 *
	 * @type {Object}
	 */
	var D_ALTERNATE_WYSIWYG_STRING_MODE = {
		className: 'string',
		begin: '`',
		end: '`[cwd]?'
	};

	/**
	 * D hexadecimal string literal
	 *
	 * @type {Object}
	 */
	var D_HEX_STRING_MODE = {
		className: 'string',
		begin: 'x"[\\da-fA-F\\s\\n\\r]*"[cwd]?',
		relevance: 10
	};

	/**
	 * D delimited string literal
	 *
	 * @type {Object}
	 */
	var D_TOKEN_STRING_MODE = {
		className: 'string',
		begin: 'q"\\{',
		end: '\\}"'
	};

	/**
	 * Hashbang support
	 *
	 * @type {Object}
	 */
	var D_HASHBANG_MODE = {
		className: 'meta',
		begin: '^#!',
		end: '$',
		relevance: 5
	};

	/**
	 * D special token sequence
	 *
	 * @type {Object}
	 */
	var D_SPECIAL_TOKEN_SEQUENCE_MODE = {
		className: 'meta',
		begin: '#(line)',
		end: '$',
		relevance: 5
	};

	/**
	 * D attributes
	 *
	 * @type {Object}
	 */
	var D_ATTRIBUTE_MODE = {
		className: 'keyword',
		begin: '@[a-zA-Z_][a-zA-Z_\\d]*'
	};

	/**
	 * D nesting comment
	 *
	 * @type {Object}
	 */
	var D_NESTING_COMMENT_MODE = hljs.COMMENT(
		'\\/\\+',
		'\\+\\/',
		{
			contains: ['self'],
			relevance: 10
		}
	);

	return {
		lexemes: hljs.UNDERSCORE_IDENT_RE,
		keywords: D_KEYWORDS,
		contains: [
			hljs.C_LINE_COMMENT_MODE,
				hljs.C_BLOCK_COMMENT_MODE,
				D_NESTING_COMMENT_MODE,
				D_HEX_STRING_MODE,
				D_STRING_MODE,
				D_WYSIWYG_DELIMITED_STRING_MODE,
				D_ALTERNATE_WYSIWYG_STRING_MODE,
				D_TOKEN_STRING_MODE,
				D_FLOAT_MODE,
				D_INTEGER_MODE,
				D_CHARACTER_MODE,
				D_HASHBANG_MODE,
				D_SPECIAL_TOKEN_SEQUENCE_MODE,
				D_ATTRIBUTE_MODE
		]
	};
}
);

// #END

// === lang/delphi.js

/*
Language: Delphi
*/

// syntax/lang/delphi.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('delphi',
function(hljs) {
	var KEYWORDS =
		'exports register file shl array record property for mod while set ally label uses raise not ' +
		'stored class safecall var interface or private static exit index inherited to else stdcall ' +
		'override shr asm far resourcestring finalization packed virtual out and protected library do ' +
		'xorwrite goto near function end div overload object unit begin string on inline repeat until ' +
		'destructor write message program with read initialization except default nil if case cdecl in ' +
		'downto threadvar of try pascal const external constructor type public then implementation ' +
		'finally published procedure absolute reintroduce operator as is abstract alias assembler ' +
		'bitpacked break continue cppdecl cvar enumerator experimental platform deprecated ' +
		'unimplemented dynamic export far16 forward generic helper implements interrupt iochecks ' +
		'local name nodefault noreturn nostackframe oldfpccall otherwise saveregisters softfloat ' +
		'specialize strict unaligned varargs ';
	var COMMENT_MODES = [
		hljs.C_LINE_COMMENT_MODE,
		hljs.COMMENT(/\{/, /\}/, {relevance: 0}),
		hljs.COMMENT(/\(\*/, /\*\)/, {relevance: 10})
	];
	var DIRECTIVE = {
		className: 'meta',
		variants: [
			{begin: /\{\$/, end: /\}/},
			{begin: /\(\*\$/, end: /\*\)/}
		]
	};
	var STRING = {
		className: 'string',
		begin: /'/, end: /'/,
		contains: [{begin: /''/}]
	};
	var CHAR_STRING = {
		className: 'string', begin: /(#\d+)+/
	};
	var CLASS = {
		begin: hljs.IDENT_RE + '\\s*=\\s*class\\s*\\(', returnBegin: true,
		contains: [
			hljs.TITLE_MODE
		]
	};
	var FUNCTION = {
		className: 'function',
		beginKeywords: 'function constructor destructor procedure', end: /[:;]/,
		keywords: 'function constructor|10 destructor|10 procedure|10',
		contains: [
			hljs.TITLE_MODE,
			{
				className: 'params',
				begin: /\(/, end: /\)/,
				keywords: KEYWORDS,
				contains: [STRING, CHAR_STRING, DIRECTIVE].concat(COMMENT_MODES)
			},
			DIRECTIVE
		].concat(COMMENT_MODES)
	};
	return {
		aliases: ['dpr', 'dfm', 'pas', 'pascal', 'freepascal', 'lazarus', 'lpr', 'lfm'],
		case_insensitive: true,
		keywords: KEYWORDS,
		illegal: /"|\$[G-Zg-z]|\/\*|<\/|\|/,
		contains: [
			STRING, CHAR_STRING,
			hljs.NUMBER_MODE,
			CLASS,
			FUNCTION,
			DIRECTIVE
		].concat(COMMENT_MODES)
	};
}
);

// #END

// === lang/erlang.js

/*
Language: Erlang
Description: Erlang is a general-purpose functional language, with strict evaluation, single assignment, and dynamic typing.
Author: Nikolay Zakharov <nikolay.desh@gmail.com>, Dmitry Kovega <arhibot@gmail.com>
Category: functional
*/

// syntax/lang/erlang.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('erlang',
function(hljs) {
	var BASIC_ATOM_RE = '[a-z\'][a-zA-Z0-9_\']*';
	var FUNCTION_NAME_RE = '(' + BASIC_ATOM_RE + ':' + BASIC_ATOM_RE + '|' + BASIC_ATOM_RE + ')';
	var ERLANG_RESERVED = {
		keyword:
			'after and andalso|10 band begin bnot bor bsl bzr bxor case catch cond div end fun if ' +
			'let not of orelse|10 query receive rem try when xor',
		literal:
			'false true'
	};

	var COMMENT = hljs.COMMENT('%', '$');
	var NUMBER = {
		className: 'number',
		begin: '\\b(\\d+#[a-fA-F0-9]+|\\d+(\\.\\d+)?([eE][-+]?\\d+)?)',
		relevance: 0
	};
	var NAMED_FUN = {
		begin: 'fun\\s+' + BASIC_ATOM_RE + '/\\d+'
	};
	var FUNCTION_CALL = {
		begin: FUNCTION_NAME_RE + '\\(', end: '\\)',
		returnBegin: true,
		relevance: 0,
		contains: [
			{
				begin: FUNCTION_NAME_RE, relevance: 0
			},
			{
				begin: '\\(', end: '\\)', endsWithParent: true,
				returnEnd: true,
				relevance: 0
				// "contains" defined later
			}
		]
	};
	var TUPLE = {
		begin: '{', end: '}',
		relevance: 0
		// "contains" defined later
	};
	var VAR1 = {
		begin: '\\b_([A-Z][A-Za-z0-9_]*)?',
		relevance: 0
	};
	var VAR2 = {
		begin: '[A-Z][a-zA-Z0-9_]*',
		relevance: 0
	};
	var RECORD_ACCESS = {
		begin: '#' + hljs.UNDERSCORE_IDENT_RE,
		relevance: 0,
		returnBegin: true,
		contains: [
			{
				begin: '#' + hljs.UNDERSCORE_IDENT_RE,
				relevance: 0
			},
			{
				begin: '{', end: '}',
				relevance: 0
				// "contains" defined later
			}
		]
	};

	var BLOCK_STATEMENTS = {
		beginKeywords: 'fun receive if try case', end: 'end',
		keywords: ERLANG_RESERVED
	};
	BLOCK_STATEMENTS.contains = [
		COMMENT,
		NAMED_FUN,
		hljs.inherit(hljs.APOS_STRING_MODE, {className: ''}),
		BLOCK_STATEMENTS,
		FUNCTION_CALL,
		hljs.QUOTE_STRING_MODE,
		NUMBER,
		TUPLE,
		VAR1, VAR2,
		RECORD_ACCESS
	];

	var BASIC_MODES = [
		COMMENT,
		NAMED_FUN,
		BLOCK_STATEMENTS,
		FUNCTION_CALL,
		hljs.QUOTE_STRING_MODE,
		NUMBER,
		TUPLE,
		VAR1, VAR2,
		RECORD_ACCESS
	];
	FUNCTION_CALL.contains[1].contains = BASIC_MODES;
	TUPLE.contains = BASIC_MODES;
	RECORD_ACCESS.contains[1].contains = BASIC_MODES;

	var PARAMS = {
		className: 'params',
		begin: '\\(', end: '\\)',
		contains: BASIC_MODES
	};
	return {
		aliases: ['erl'],
		keywords: ERLANG_RESERVED,
		illegal: '(</|\\*=|\\+=|-=|/\\*|\\*/|\\(\\*|\\*\\))',
		contains: [
			{
				className: 'function',
				begin: '^' + BASIC_ATOM_RE + '\\s*\\(', end: '->',
				returnBegin: true,
				illegal: '\\(|#|//|/\\*|\\\\|:|;',
				contains: [
					PARAMS,
					hljs.inherit(hljs.TITLE_MODE, {begin: BASIC_ATOM_RE})
				],
				starts: {
					end: ';|\\.',
					keywords: ERLANG_RESERVED,
					contains: BASIC_MODES
				}
			},
			COMMENT,
			{
				begin: '^-', end: '\\.',
				relevance: 0,
				excludeEnd: true,
				returnBegin: true,
				lexemes: '-' + hljs.IDENT_RE,
				keywords:
					'-module -record -undef -export -ifdef -ifndef -author -copyright -doc -vsn ' +
					'-import -include -include_lib -compile -define -else -endif -file -behaviour ' +
					'-behavior -spec',
				contains: [PARAMS]
			},
			NUMBER,
			hljs.QUOTE_STRING_MODE,
			RECORD_ACCESS,
			VAR1, VAR2,
			TUPLE,
			{begin: /\.$/} // relevance booster
		]
	};
}
);

// #END

// === lang/fortran.js

/*
Language: Fortran
Author: Anthony Scemama <scemama@irsamc.ups-tlse.fr>
Category: scientific
*/

// syntax/lang/fortran.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('fortran',
function(hljs) {
	var PARAMS = {
		className: 'params',
		begin: '\\(', end: '\\)'
	};

	var F_KEYWORDS = {
		literal: '.False. .True.',
		keyword: 'kind do while private call intrinsic where elsewhere ' +
			'type endtype endmodule endselect endinterface end enddo endif if forall endforall only contains default return stop then ' +
			'public subroutine|10 function program .and. .or. .not. .le. .eq. .ge. .gt. .lt. ' +
			'goto save else use module select case ' +
			'access blank direct exist file fmt form formatted iostat name named nextrec number opened rec recl sequential status unformatted unit ' +
			'continue format pause cycle exit ' +
			'c_null_char c_alert c_backspace c_form_feed flush wait decimal round iomsg ' +
			'synchronous nopass non_overridable pass protected volatile abstract extends import ' +
			'non_intrinsic value deferred generic final enumerator class associate bind enum ' +
			'c_int c_short c_long c_long_long c_signed_char c_size_t c_int8_t c_int16_t c_int32_t c_int64_t c_int_least8_t c_int_least16_t ' +
			'c_int_least32_t c_int_least64_t c_int_fast8_t c_int_fast16_t c_int_fast32_t c_int_fast64_t c_intmax_t C_intptr_t c_float c_double ' +
			'c_long_double c_float_complex c_double_complex c_long_double_complex c_bool c_char c_null_ptr c_null_funptr ' +
			'c_new_line c_carriage_return c_horizontal_tab c_vertical_tab iso_c_binding c_loc c_funloc c_associated  c_f_pointer ' +
			'c_ptr c_funptr iso_fortran_env character_storage_size error_unit file_storage_size input_unit iostat_end iostat_eor ' +
			'numeric_storage_size output_unit c_f_procpointer ieee_arithmetic ieee_support_underflow_control ' +
			'ieee_get_underflow_mode ieee_set_underflow_mode newunit contiguous recursive ' +
			'pad position action delim readwrite eor advance nml interface procedure namelist include sequence elemental pure ' +
			'integer real character complex logical dimension allocatable|10 parameter ' +
			'external implicit|10 none double precision assign intent optional pointer ' +
			'target in out common equivalence data',
		built_in: 'alog alog10 amax0 amax1 amin0 amin1 amod cabs ccos cexp clog csin csqrt dabs dacos dasin datan datan2 dcos dcosh ddim dexp dint ' +
			'dlog dlog10 dmax1 dmin1 dmod dnint dsign dsin dsinh dsqrt dtan dtanh float iabs idim idint idnint ifix isign max0 max1 min0 min1 sngl ' +
			'algama cdabs cdcos cdexp cdlog cdsin cdsqrt cqabs cqcos cqexp cqlog cqsin cqsqrt dcmplx dconjg derf derfc dfloat dgamma dimag dlgama ' +
			'iqint qabs qacos qasin qatan qatan2 qcmplx qconjg qcos qcosh qdim qerf qerfc qexp qgamma qimag qlgama qlog qlog10 qmax1 qmin1 qmod ' +
			'qnint qsign qsin qsinh qsqrt qtan qtanh abs acos aimag aint anint asin atan atan2 char cmplx conjg cos cosh exp ichar index int log ' +
			'log10 max min nint sign sin sinh sqrt tan tanh print write dim lge lgt lle llt mod nullify allocate deallocate ' +
			'adjustl adjustr all allocated any associated bit_size btest ceiling count cshift date_and_time digits dot_product ' +
			'eoshift epsilon exponent floor fraction huge iand ibclr ibits ibset ieor ior ishft ishftc lbound len_trim matmul ' +
			'maxexponent maxloc maxval merge minexponent minloc minval modulo mvbits nearest pack present product ' +
			'radix random_number random_seed range repeat reshape rrspacing scale scan selected_int_kind selected_real_kind ' +
			'set_exponent shape size spacing spread sum system_clock tiny transpose trim ubound unpack verify achar iachar transfer ' +
			'dble entry dprod cpu_time command_argument_count get_command get_command_argument get_environment_variable is_iostat_end ' +
			'ieee_arithmetic ieee_support_underflow_control ieee_get_underflow_mode ieee_set_underflow_mode ' +
			'is_iostat_eor move_alloc new_line selected_char_kind same_type_as extends_type_of'  +
			'acosh asinh atanh bessel_j0 bessel_j1 bessel_jn bessel_y0 bessel_y1 bessel_yn erf erfc erfc_scaled gamma log_gamma hypot norm2 ' +
			'atomic_define atomic_ref execute_command_line leadz trailz storage_size merge_bits ' +
			'bge bgt ble blt dshiftl dshiftr findloc iall iany iparity image_index lcobound ucobound maskl maskr ' +
			'num_images parity popcnt poppar shifta shiftl shiftr this_image'
	};
	return {
		case_insensitive: true,
		aliases: ['f90', 'f95'],
		keywords: F_KEYWORDS,
		illegal: /\/\*/,
		contains: [
			hljs.inherit(hljs.APOS_STRING_MODE, {className: 'string', relevance: 0}),
			hljs.inherit(hljs.QUOTE_STRING_MODE, {className: 'string', relevance: 0}),
			{
				className: 'function',
				beginKeywords: 'subroutine function program',
				illegal: '[${=\\n]',
				contains: [hljs.UNDERSCORE_TITLE_MODE, PARAMS]
			},
			hljs.COMMENT('!', '$', {relevance: 0}),
			{
				className: 'number',
				begin: '(?=\\b|\\+|\\-|\\.)(?=\\.\\d|\\d)(?:\\d+)?(?:\\.?\\d*)(?:[de][+-]?\\d+)?\\b\\.?',
				relevance: 0
			}
		]
	};
}
);

// #END

// === lang/fsharp.js

/*
Language: F#
Author: Jonas Follesø <jonas@follesoe.no>
Contributors: Troy Kershaw <hello@troykershaw.com>, Henrik Feldt <henrik@haf.se>
Category: functional
*/

// syntax/lang/fsharp.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('fsharp',
function(hljs) {
	var TYPEPARAM = {
		begin: '<', end: '>',
		contains: [
			hljs.inherit(hljs.TITLE_MODE, {begin: /'[a-zA-Z0-9_]+/})
		]
	};

	return {
		aliases: ['fs'],
		keywords:
			'abstract and as assert base begin class default delegate do done ' +
			'downcast downto elif else end exception extern false finally for ' +
			'fun function global if in inherit inline interface internal lazy let ' +
			'match member module mutable namespace new null of open or ' +
			'override private public rec return sig static struct then to ' +
			'true try type upcast use val void when while with yield',
		illegal: /\/\*/,
		contains: [
			{
				// monad builder keywords (matches before non-bang kws)
				className: 'keyword',
				begin: /\b(yield|return|let|do)!/
			},
			{
				className: 'string',
				begin: '@"', end: '"',
				contains: [{begin: '""'}]
			},
			{
				className: 'string',
				begin: '"""', end: '"""'
			},
			hljs.COMMENT('\\(\\*', '\\*\\)'),
			{
				className: 'class',
				beginKeywords: 'type', end: '\\(|=|$', excludeEnd: true,
				contains: [
					hljs.UNDERSCORE_TITLE_MODE,
					TYPEPARAM
				]
			},
			{
				className: 'meta',
				begin: '\\[<', end: '>\\]',
				relevance: 10
			},
			{
				className: 'symbol',
				begin: '\\B(\'[A-Za-z])\\b',
				contains: [hljs.BACKSLASH_ESCAPE]
			},
			hljs.C_LINE_COMMENT_MODE,
			hljs.inherit(hljs.QUOTE_STRING_MODE, {illegal: null}),
			hljs.C_NUMBER_MODE
		]
	};
}
);

// #END

// === lang/groovy.js

/*
Language: Groovy
Author: Guillaume Laforge <glaforge@gmail.com>
Description: Groovy programming language implementation inspired from Vsevolod's Java mode
Website: https://groovy-lang.org
*/

// syntax/lang/groovy.js
// HighlightJs: v.9.16.2

hljs.registerLanguage('groovy',
function(hljs) {
	return {
		keywords: {
			literal : 'true false null',
			keyword:
			'byte short char int long boolean float double void ' +
			// groovy specific keywords
			'def as in assert trait ' +
			// common keywords with Java
			'super this abstract static volatile transient public private protected synchronized final ' +
			'class interface enum if else for while switch case break default continue ' +
			'throw throws try catch finally implements extends new import package return instanceof'
		},
		contains: [
			hljs.COMMENT(
				'/\\*\\*',
				'\\*/',
				{
					relevance : 0,
					contains : [
					  {
						  // eat up @'s in emails to prevent them to be recognized as doctags
						  begin: /\w+@/, relevance: 0
					  },
					  {
						  className : 'doctag',
						  begin : '@[A-Za-z]+'
					  }
					]
				}
			),
			hljs.C_LINE_COMMENT_MODE,
			hljs.C_BLOCK_COMMENT_MODE,
			{
				className: 'string',
				begin: '"""', end: '"""'
			},
			{
				className: 'string',
				begin: "'''", end: "'''"
			},
			{
				className: 'string',
				begin: "\\$/", end: "/\\$",
				relevance: 10
			},
			hljs.APOS_STRING_MODE,
			{
				className: 'regexp',
				begin: /~?\/[^\/\n]+\//,
				contains: [
					hljs.BACKSLASH_ESCAPE
				]
			},
			hljs.QUOTE_STRING_MODE,
			{
				className: 'meta',
				begin: "^#!/usr/bin/env", end: '$',
				illegal: '\n'
			},
			hljs.BINARY_NUMBER_MODE,
			{
				className: 'class',
				beginKeywords: 'class interface trait enum', end: '{',
				illegal: ':',
				contains: [
					{beginKeywords: 'extends implements'},
					hljs.UNDERSCORE_TITLE_MODE
				]
			},
			hljs.C_NUMBER_MODE,
			{
				className: 'meta', begin: '@[A-Za-z]+'
			},
			{
				// highlight map keys and named parameters as strings
				className: 'string', begin: /[^\?]{0}[A-Za-z0-9_$]+ *:/
			},
			{
				// catch middle element of the ternary operator
				// to avoid highlight it as a label, named parameter, or map key
				begin: /\?/, end: /\:/
			},
			{
				// highlight labeled statements
				className: 'symbol', begin: '^\\s*[A-Za-z0-9_$]+:',
				relevance: 0
			}
		],
		illegal: /#|<\//
	}
}
);

// #END

// === lang/haskell.js

/*
Language: Haskell
Author: Jeremy Hull <sourdrums@gmail.com>
Contributors: Zena Treep <zena.treep@gmail.com>
Category: functional
*/

// syntax/lang/haskell.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('haskell',
function(hljs) {
	var COMMENT = {
		variants: [
			hljs.COMMENT('--', '$'),
			hljs.COMMENT(
				'{-',
				'-}',
				{
					contains: ['self']
				}
			)
		]
	};

	var PRAGMA = {
		className: 'meta',
		begin: '{-#', end: '#-}'
	};

	var PREPROCESSOR = {
		className: 'meta',
		begin: '^#', end: '$'
	};

	var CONSTRUCTOR = {
		className: 'type',
		begin: '\\b[A-Z][\\w\']*', // TODO: other constructors (build-in, infix).
		relevance: 0
	};

	var LIST = {
		begin: '\\(', end: '\\)',
		illegal: '"',
		contains: [
			PRAGMA,
			PREPROCESSOR,
			{className: 'type', begin: '\\b[A-Z][\\w]*(\\((\\.\\.|,|\\w+)\\))?'},
			hljs.inherit(hljs.TITLE_MODE, {begin: '[_a-z][\\w\']*'}),
			COMMENT
		]
	};

	var RECORD = {
		begin: '{', end: '}',
		contains: LIST.contains
	};

	return {
		aliases: ['hs'],
		keywords:
			'let in if then else case of where do module import hiding ' +
			'qualified type data newtype deriving class instance as default ' +
			'infix infixl infixr foreign export ccall stdcall cplusplus ' +
			'jvm dotnet safe unsafe family forall mdo proc rec',
		contains: [

			// Top-level constructions.

			{
				beginKeywords: 'module', end: 'where',
				keywords: 'module where',
				contains: [LIST, COMMENT],
				illegal: '\\W\\.|;'
			},
			{
				begin: '\\bimport\\b', end: '$',
				keywords: 'import qualified as hiding',
				contains: [LIST, COMMENT],
				illegal: '\\W\\.|;'
			},

			{
				className: 'class',
				begin: '^(\\s*)?(class|instance)\\b', end: 'where',
				keywords: 'class family instance where',
				contains: [CONSTRUCTOR, LIST, COMMENT]
			},
			{
				className: 'class',
				begin: '\\b(data|(new)?type)\\b', end: '$',
				keywords: 'data family type newtype deriving',
				contains: [PRAGMA, CONSTRUCTOR, LIST, RECORD, COMMENT]
			},
			{
				beginKeywords: 'default', end: '$',
				contains: [CONSTRUCTOR, LIST, COMMENT]
			},
			{
				beginKeywords: 'infix infixl infixr', end: '$',
				contains: [hljs.C_NUMBER_MODE, COMMENT]
			},
			{
				begin: '\\bforeign\\b', end: '$',
				keywords: 'foreign import export ccall stdcall cplusplus jvm ' +
									'dotnet safe unsafe',
				contains: [CONSTRUCTOR, hljs.QUOTE_STRING_MODE, COMMENT]
			},
			{
				className: 'meta',
				begin: '#!\\/usr\\/bin\\/env\ runhaskell', end: '$'
			},

			// "Whitespaces".

			PRAGMA,
			PREPROCESSOR,

			// Literals and names.

			// TODO: characters.
			hljs.QUOTE_STRING_MODE,
			hljs.C_NUMBER_MODE,
			CONSTRUCTOR,
			hljs.inherit(hljs.TITLE_MODE, {begin: '^[_a-z][\\w\']*'}),

			COMMENT,

			{begin: '->|<-'} // No markup, relevance booster
		]
	};
}
);

// #END

// === lang/haxe.js

/*
Language: Haxe
Author: Christopher Kaster <ikasoki@gmail.com> (Based on the actionscript.js language file by Alexander Myadzel)
Contributors: Kenton Hamaluik <kentonh@gmail.com>
*/

// syntax/lang/haxe.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('haxe',
function(hljs) {
	var IDENT_RE = '[a-zA-Z_$][a-zA-Z0-9_$]*';
	var IDENT_FUNC_RETURN_TYPE_RE = '([*]|[a-zA-Z_$][a-zA-Z0-9_$]*)';

	var HAXE_BASIC_TYPES = 'Int Float String Bool Dynamic Void Array ';

	return {
		aliases: ['hx'],
		keywords: {
			keyword: 'break case cast catch continue default do dynamic else enum extern ' +
							 'for function here if import in inline never new override package private get set ' +
							 'public return static super switch this throw trace try typedef untyped using var while ' +
							 HAXE_BASIC_TYPES,
			built_in:
				'trace this',
			literal:
				'true false null _'
		},
		contains: [
			{ className: 'string', // interpolate-able strings
				begin: '\'', end: '\'',
				contains: [
					hljs.BACKSLASH_ESCAPE,
					{ className: 'subst', // interpolation
						begin: '\\$\\{', end: '\\}'
					},
					{ className: 'subst', // interpolation
						begin: '\\$', end: '\\W}'
					}
				]
			},
			hljs.QUOTE_STRING_MODE,
			hljs.C_LINE_COMMENT_MODE,
			hljs.C_BLOCK_COMMENT_MODE,
			hljs.C_NUMBER_MODE,
			{ className: 'meta', // compiler meta
				begin: '@:', end: '$'
			},
			{ className: 'meta', // compiler conditionals
				begin: '#', end: '$',
				keywords: {'meta-keyword': 'if else elseif end error'}
			},
			{ className: 'type', // function types
				begin: ':[ \t]*', end: '[^A-Za-z0-9_ \t\\->]',
				excludeBegin: true, excludeEnd: true,
				relevance: 0
			},
			{ className: 'type', // types
				begin: ':[ \t]*', end: '\\W',
				excludeBegin: true, excludeEnd: true
			},
			{ className: 'type', // instantiation
				begin: 'new *', end: '\\W',
				excludeBegin: true, excludeEnd: true
			},
			{ className: 'class', // enums
				beginKeywords: 'enum', end: '\\{',
				contains: [
					hljs.TITLE_MODE
				]
			},
			{ className: 'class', // abstracts
				beginKeywords: 'abstract', end: '[\\{$]',
				contains: [
					{ className: 'type',
						begin: '\\(', end: '\\)',
						excludeBegin: true, excludeEnd: true
					},
					{ className: 'type',
						begin: 'from +', end: '\\W',
						excludeBegin: true, excludeEnd: true
					},
					{ className: 'type',
						begin: 'to +', end: '\\W',
						excludeBegin: true, excludeEnd: true
					},
					hljs.TITLE_MODE
				],
				keywords: {
					keyword: 'abstract from to'
				}
			},
			{ className: 'class', // classes
				begin: '\\b(class|interface) +', end: '[\\{$]',  excludeEnd: true,
				keywords: 'class interface',
				contains: [
					{ className: 'keyword',
						begin: '\\b(extends|implements) +',
						keywords: 'extends implements',
						contains: [
							{
								className: 'type',
								begin: hljs.IDENT_RE,
								relevance: 0
							}
						]
					},
					hljs.TITLE_MODE
				]
			},
			{ className: 'function',
				beginKeywords: 'function', end: '\\(', excludeEnd: true,
				illegal: '\\S',
				contains: [
					hljs.TITLE_MODE
				]
			}
		],
		illegal: /<\//
	};
}
);

// #END

// === lang/java.js

/*
Language: Java
Author: Vsevolod Solovyov <vsevolod.solovyov@gmail.com>
Category: common, enterprise
*/

// syntax/lang/java.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('java',
function(hljs) {
	var JAVA_IDENT_RE = '[\u00C0-\u02B8a-zA-Z_$][\u00C0-\u02B8a-zA-Z_$0-9]*';
	var GENERIC_IDENT_RE = JAVA_IDENT_RE + '(<' + JAVA_IDENT_RE + '(\\s*,\\s*' + JAVA_IDENT_RE + ')*>)?';
	var KEYWORDS =
		'false synchronized int abstract float private char boolean var static null if const ' +
		'for true while long strictfp finally protected import native final void ' +
		'enum else break transient catch instanceof byte super volatile case assert short ' +
		'package default double public try this switch continue throws protected public private ' +
		'module requires exports do';

	// https://docs.oracle.com/javase/7/docs/technotes/guides/language/underscores-literals.html
	var JAVA_NUMBER_RE = '\\b' +
		'(' +
			'0[bB]([01]+[01_]+[01]+|[01]+)' + // 0b...
			'|' +
			'0[xX]([a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|[a-fA-F0-9]+)' + // 0x...
			'|' +
			'(' +
				'([\\d]+[\\d_]+[\\d]+|[\\d]+)(\\.([\\d]+[\\d_]+[\\d]+|[\\d]+))?' +
				'|' +
				'\\.([\\d]+[\\d_]+[\\d]+|[\\d]+)' +
			')' +
			'([eE][-+]?\\d+)?' + // octal, decimal, float
		')' +
		'[lLfF]?';
	var JAVA_NUMBER_MODE = {
		className: 'number',
		begin: JAVA_NUMBER_RE,
		relevance: 0
	};

	return {
		aliases: ['jsp'],
		keywords: KEYWORDS,
		illegal: /<\/|#/,
		contains: [
			hljs.COMMENT(
				'/\\*\\*',
				'\\*/',
				{
					relevance : 0,
					contains : [
						{
							// eat up @'s in emails to prevent them to be recognized as doctags
							begin: /\w+@/, relevance: 0
						},
						{
							className : 'doctag',
							begin : '@[A-Za-z]+'
						}
					]
				}
			),
			hljs.C_LINE_COMMENT_MODE,
			hljs.C_BLOCK_COMMENT_MODE,
			hljs.APOS_STRING_MODE,
			hljs.QUOTE_STRING_MODE,
			{
				className: 'class',
				beginKeywords: 'class interface', end: /[{;=]/, excludeEnd: true,
				keywords: 'class interface',
				illegal: /[:"\[\]]/,
				contains: [
					{beginKeywords: 'extends implements'},
					hljs.UNDERSCORE_TITLE_MODE
				]
			},
			{
				// Expression keywords prevent 'keyword Name(...)' from being
				// recognized as a function definition
				beginKeywords: 'new throw return else',
				relevance: 0
			},
			{
				className: 'function',
				begin: '(' + GENERIC_IDENT_RE + '\\s+)+' + hljs.UNDERSCORE_IDENT_RE + '\\s*\\(', returnBegin: true, end: /[{;=]/,
				excludeEnd: true,
				keywords: KEYWORDS,
				contains: [
					{
						begin: hljs.UNDERSCORE_IDENT_RE + '\\s*\\(', returnBegin: true,
						relevance: 0,
						contains: [hljs.UNDERSCORE_TITLE_MODE]
					},
					{
						className: 'params',
						begin: /\(/, end: /\)/,
						keywords: KEYWORDS,
						relevance: 0,
						contains: [
							hljs.APOS_STRING_MODE,
							hljs.QUOTE_STRING_MODE,
							hljs.C_NUMBER_MODE,
							hljs.C_BLOCK_COMMENT_MODE
						]
					},
					hljs.C_LINE_COMMENT_MODE,
					hljs.C_BLOCK_COMMENT_MODE
				]
			},
			JAVA_NUMBER_MODE,
			{
				className: 'meta', begin: '@[A-Za-z]+'
			}
		]
	};
}
);

// #END

// === lang/kotlin.js

/*
Language: Kotlin
Description: Kotlin is an OSS statically typed programming language that targets the JVM, Android, JavaScript and Native.
Author: Sergey Mashkov <cy6erGn0m@gmail.com>
Website: https://kotlinlang.org
Category: common
*/

// syntax/lang/kotlin.js
// HighlightJs: v.9.16.2

hljs.registerLanguage('kotlin',
function(hljs) {
	var KEYWORDS = {
		keyword:
			'abstract as val var vararg get set class object open private protected public noinline ' +
			'crossinline dynamic final enum if else do while for when throw try catch finally ' +
			'import package is in fun override companion reified inline lateinit init ' +
			'interface annotation data sealed internal infix operator out by constructor super ' +
			'tailrec where const inner suspend typealias external expect actual ' +
			// to be deleted soon
			'trait volatile transient native default',
		built_in:
			'Byte Short Char Int Long Boolean Float Double Void Unit Nothing',
		literal:
			'true false null'
	};
	var KEYWORDS_WITH_LABEL = {
		className: 'keyword',
		begin: /\b(break|continue|return|this)\b/,
		starts: {
			contains: [
				{
					className: 'symbol',
					begin: /@\w+/
				}
			]
		}
	};
	var LABEL = {
		className: 'symbol', begin: hljs.UNDERSCORE_IDENT_RE + '@'
	};

	// for string templates
	var SUBST = {
		className: 'subst',
		begin: '\\${', end: '}', contains: [hljs.C_NUMBER_MODE]
	};
	var VARIABLE = {
		className: 'variable', begin: '\\$' + hljs.UNDERSCORE_IDENT_RE
	};
	var STRING = {
		className: 'string',
		variants: [
			{
				begin: '"""', end: '"""',
				contains: [VARIABLE, SUBST]
			},
			// Can't use built-in modes easily, as we want to use STRING in the meta
			// context as 'meta-string' and there's no syntax to remove explicitly set
			// classNames in built-in modes.
			{
				begin: '\'', end: '\'',
				illegal: /\n/,
				contains: [hljs.BACKSLASH_ESCAPE]
			},
			{
				begin: '"', end: '"',
				illegal: /\n/,
				contains: [hljs.BACKSLASH_ESCAPE, VARIABLE, SUBST]
			}
		]
	};
	SUBST.contains.push(STRING)

	var ANNOTATION_USE_SITE = {
		className: 'meta', begin: '@(?:file|property|field|get|set|receiver|param|setparam|delegate)\\s*:(?:\\s*' + hljs.UNDERSCORE_IDENT_RE + ')?'
	};
	var ANNOTATION = {
		className: 'meta', begin: '@' + hljs.UNDERSCORE_IDENT_RE,
		contains: [
			{
				begin: /\(/, end: /\)/,
				contains: [
					hljs.inherit(STRING, {className: 'meta-string'})
				]
			}
		]
	};

	// https://kotlinlang.org/docs/reference/whatsnew11.html#underscores-in-numeric-literals
	// According to the doc above, the number mode of kotlin is the same as java 8,
	// so the code below is copied from java.js
	var KOTLIN_NUMBER_RE = '\\b' +
		'(' +
			'0[bB]([01]+[01_]+[01]+|[01]+)' + // 0b...
			'|' +
			'0[xX]([a-fA-F0-9]+[a-fA-F0-9_]+[a-fA-F0-9]+|[a-fA-F0-9]+)' + // 0x...
			'|' +
			'(' +
				'([\\d]+[\\d_]+[\\d]+|[\\d]+)(\\.([\\d]+[\\d_]+[\\d]+|[\\d]+))?' +
				'|' +
				'\\.([\\d]+[\\d_]+[\\d]+|[\\d]+)' +
			')' +
			'([eE][-+]?\\d+)?' + // octal, decimal, float
		')' +
		'[lLfF]?';
	var KOTLIN_NUMBER_MODE = {
		className: 'number',
		begin: KOTLIN_NUMBER_RE,
		relevance: 0
	};
	var KOTLIN_NESTED_COMMENT = hljs.COMMENT(
		'/\\*', '\\*/',
		{ contains: [ hljs.C_BLOCK_COMMENT_MODE ] }
	);
	var KOTLIN_PAREN_TYPE = {
		variants: [
		{ className: 'type',
			begin: hljs.UNDERSCORE_IDENT_RE
		},
		{ begin: /\(/, end: /\)/,
			contains: [] //defined later
		}
	]
	};
	var KOTLIN_PAREN_TYPE2 = KOTLIN_PAREN_TYPE;
	KOTLIN_PAREN_TYPE2.variants[1].contains = [ KOTLIN_PAREN_TYPE ];
	KOTLIN_PAREN_TYPE.variants[1].contains = [ KOTLIN_PAREN_TYPE2 ];

	return {
		aliases: ['kt'],
		keywords: KEYWORDS,
		contains : [
			hljs.COMMENT(
				'/\\*\\*',
				'\\*/',
				{
					relevance : 0,
					contains : [{
						className : 'doctag',
						begin : '@[A-Za-z]+'
					}]
				}
			),
			hljs.C_LINE_COMMENT_MODE,
			KOTLIN_NESTED_COMMENT,
			KEYWORDS_WITH_LABEL,
			LABEL,
			ANNOTATION_USE_SITE,
			ANNOTATION,
			{
				className: 'function',
				beginKeywords: 'fun', end: '[(]|$',
				returnBegin: true,
				excludeEnd: true,
				keywords: KEYWORDS,
				illegal: /fun\s+(<.*>)?[^\s\(]+(\s+[^\s\(]+)\s*=/,
				relevance: 5,
				contains: [
					{
						begin: hljs.UNDERSCORE_IDENT_RE + '\\s*\\(', returnBegin: true,
						relevance: 0,
						contains: [hljs.UNDERSCORE_TITLE_MODE]
					},
					{
						className: 'type',
						begin: /</, end: />/, keywords: 'reified',
						relevance: 0
					},
					{
						className: 'params',
						begin: /\(/, end: /\)/,
						endsParent: true,
						keywords: KEYWORDS,
						relevance: 0,
						contains: [
							{
								begin: /:/, end: /[=,\/]/, endsWithParent: true,
								contains: [
									KOTLIN_PAREN_TYPE,
									hljs.C_LINE_COMMENT_MODE,
									KOTLIN_NESTED_COMMENT
								],
								relevance: 0
							},
							hljs.C_LINE_COMMENT_MODE,
							KOTLIN_NESTED_COMMENT,
							ANNOTATION_USE_SITE,
							ANNOTATION,
							STRING,
							hljs.C_NUMBER_MODE
						]
					},
					KOTLIN_NESTED_COMMENT
				]
			},
			{
				className: 'class',
				beginKeywords: 'class interface trait', end: /[:\{(]|$/, // remove 'trait' when removed from KEYWORDS
				excludeEnd: true,
				illegal: 'extends implements',
				contains: [
					{beginKeywords: 'public protected internal private constructor'},
					hljs.UNDERSCORE_TITLE_MODE,
					{
						className: 'type',
						begin: /</, end: />/, excludeBegin: true, excludeEnd: true,
						relevance: 0
					},
					{
						className: 'type',
						begin: /[,:]\s*/, end: /[<\(,]|$/, excludeBegin: true, returnEnd: true
					},
					ANNOTATION_USE_SITE,
					ANNOTATION
				]
			},
			STRING,
			{
				className: 'meta',
				begin: "^#!/usr/bin/env", end: '$',
				illegal: '\n'
			},
			KOTLIN_NUMBER_MODE
		]
	};
}
);

// #END

// === lang/objectivec.js

/*
Language: Objective-C
Author: Valerii Hiora <valerii.hiora@gmail.com>
Contributors: Angel G. Olloqui <angelgarcia.mail@gmail.com>, Matt Diephouse <matt@diephouse.com>, Andrew Farmer <ahfarmer@gmail.com>, Minh Nguyễn <mxn@1ec5.org>
Category: common
*/

// syntax/lang/objectivec.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('objectivec',
function(hljs) {
	var API_CLASS = {
		className: 'built_in',
		begin: '\\b(AV|CA|CF|CG|CI|CL|CM|CN|CT|MK|MP|MTK|MTL|NS|SCN|SK|UI|WK|XC)\\w+',
	};
	var OBJC_KEYWORDS = {
		keyword:
			'int float while char export sizeof typedef const struct for union ' +
			'unsigned long volatile static bool mutable if do return goto void ' +
			'enum else break extern asm case short default double register explicit ' +
			'signed typename this switch continue wchar_t inline readonly assign ' +
			'readwrite self @synchronized id typeof ' +
			'nonatomic super unichar IBOutlet IBAction strong weak copy ' +
			'in out inout bycopy byref oneway __strong __weak __block __autoreleasing ' +
			'@private @protected @public @try @property @end @throw @catch @finally ' +
			'@autoreleasepool @synthesize @dynamic @selector @optional @required ' +
			'@encode @package @import @defs @compatibility_alias ' +
			'__bridge __bridge_transfer __bridge_retained __bridge_retain ' +
			'__covariant __contravariant __kindof ' +
			'_Nonnull _Nullable _Null_unspecified ' +
			'__FUNCTION__ __PRETTY_FUNCTION__ __attribute__ ' +
			'getter setter retain unsafe_unretained ' +
			'nonnull nullable null_unspecified null_resettable class instancetype ' +
			'NS_DESIGNATED_INITIALIZER NS_UNAVAILABLE NS_REQUIRES_SUPER ' +
			'NS_RETURNS_INNER_POINTER NS_INLINE NS_AVAILABLE NS_DEPRECATED ' +
			'NS_ENUM NS_OPTIONS NS_SWIFT_UNAVAILABLE ' +
			'NS_ASSUME_NONNULL_BEGIN NS_ASSUME_NONNULL_END ' +
			'NS_REFINED_FOR_SWIFT NS_SWIFT_NAME NS_SWIFT_NOTHROW ' +
			'NS_DURING NS_HANDLER NS_ENDHANDLER NS_VALUERETURN NS_VOIDRETURN',
		literal:
			'false true FALSE TRUE nil YES NO NULL',
		built_in:
			'BOOL dispatch_once_t dispatch_queue_t dispatch_sync dispatch_async dispatch_once'
	};
	var LEXEMES = /[a-zA-Z@][a-zA-Z0-9_]*/;
	var CLASS_KEYWORDS = '@interface @class @protocol @implementation';
	return {
		aliases: ['mm', 'objc', 'obj-c'],
		keywords: OBJC_KEYWORDS,
		lexemes: LEXEMES,
		illegal: '</',
		contains: [
			API_CLASS,
			hljs.C_LINE_COMMENT_MODE,
			hljs.C_BLOCK_COMMENT_MODE,
			hljs.C_NUMBER_MODE,
			hljs.QUOTE_STRING_MODE,
			{
				className: 'string',
				variants: [
					{
						begin: '@"', end: '"',
						illegal: '\\n',
						contains: [hljs.BACKSLASH_ESCAPE]
					},
					{
						begin: '\'', end: '[^\\\\]\'',
						illegal: '[^\\\\][^\']'
					}
				]
			},
			{
				className: 'meta',
				begin: '#',
				end: '$',
				contains: [
					{
						className: 'meta-string',
						variants: [
							{ begin: '\"', end: '\"' },
							{ begin: '<', end: '>' }
						]
					}
				]
			},
			{
				className: 'class',
				begin: '(' + CLASS_KEYWORDS.split(' ').join('|') + ')\\b', end: '({|$)', excludeEnd: true,
				keywords: CLASS_KEYWORDS, lexemes: LEXEMES,
				contains: [
					hljs.UNDERSCORE_TITLE_MODE
				]
			},
			{
				begin: '\\.'+hljs.UNDERSCORE_IDENT_RE,
				relevance: 0
			}
		]
	};
}
);

// #END

// === lang/ocaml.js

/*
Language: OCaml
Author: Mehdi Dogguy <mehdi@dogguy.org>
Contributors: Nicolas Braud-Santoni <nicolas.braud-santoni@ens-cachan.fr>, Mickael Delahaye <mickael.delahaye@gmail.com>
Description: OCaml language definition.
Category: functional
*/

// syntax/lang/ocaml.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('ocaml',
function(hljs) {
	/* missing support for heredoc-like string (OCaml 4.0.2+) */
	return {
		aliases: ['ml'],
		keywords: {
			keyword:
				'and as assert asr begin class constraint do done downto else end ' +
				'exception external for fun function functor if in include ' +
				'inherit! inherit initializer land lazy let lor lsl lsr lxor match method!|10 method ' +
				'mod module mutable new object of open! open or private rec sig struct ' +
				'then to try type val! val virtual when while with ' +
				/* camlp4 */
				'parser value',
			built_in:
				/* built-in types */
				'array bool bytes char exn|5 float int int32 int64 list lazy_t|5 nativeint|5 string unit ' +
				/* (some) types in Pervasives */
				'in_channel out_channel ref',
			literal:
				'true false'
		},
		illegal: /\/\/|>>/,
		lexemes: '[a-z_]\\w*!?',
		contains: [
			{
				className: 'literal',
				begin: '\\[(\\|\\|)?\\]|\\(\\)',
				relevance: 0
			},
			hljs.COMMENT(
				'\\(\\*',
				'\\*\\)',
				{
					contains: ['self']
				}
			),
			{ /* type variable */
				className: 'symbol',
				begin: '\'[A-Za-z_](?!\')[\\w\']*'
				/* the grammar is ambiguous on how 'a'b should be interpreted but not the compiler */
			},
			{ /* polymorphic variant */
				className: 'type',
				begin: '`[A-Z][\\w\']*'
			},
			{ /* module or constructor */
				className: 'type',
				begin: '\\b[A-Z][\\w\']*',
				relevance: 0
			},
			{ /* don't color identifiers, but safely catch all identifiers with '*/
				begin: '[a-z_]\\w*\'[\\w\']*', relevance: 0
			},
			hljs.inherit(hljs.APOS_STRING_MODE, {className: 'string', relevance: 0}),
			hljs.inherit(hljs.QUOTE_STRING_MODE, {illegal: null}),
			{
				className: 'number',
				begin:
					'\\b(0[xX][a-fA-F0-9_]+[Lln]?|' +
					'0[oO][0-7_]+[Lln]?|' +
					'0[bB][01_]+[Lln]?|' +
					'[0-9][0-9_]*([Lln]|(\\.[0-9_]*)?([eE][-+]?[0-9_]+)?)?)',
				relevance: 0
			},
			{
				begin: /[-=]>/ // relevance booster
			}
		]
	}
}
);

// #END

// === lang/openscad.js

/*
Language: OpenSCAD
Author: Dan Panzarella <alsoelp@gmail.com>
Description: OpenSCAD is a language for the 3D CAD modeling software of the same name.
Category: scientific
*/

// syntax/lang/openscad.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('openscad',
function(hljs) {
	var SPECIAL_VARS = {
		className: 'keyword',
		begin: '\\$(f[asn]|t|vp[rtd]|children)'
	},
	LITERALS = {
		className: 'literal',
		begin: 'false|true|PI|undef'
	},
	NUMBERS = {
		className: 'number',
		begin: '\\b\\d+(\\.\\d+)?(e-?\\d+)?', //adds 1e5, 1e-10
		relevance: 0
	},
	STRING = hljs.inherit(hljs.QUOTE_STRING_MODE,{illegal: null}),
	PREPRO = {
		className: 'meta',
		keywords: {'meta-keyword': 'include use'},
		begin: 'include|use <',
		end: '>'
	},
	PARAMS = {
		className: 'params',
		begin: '\\(', end: '\\)',
		contains: ['self', NUMBERS, STRING, SPECIAL_VARS, LITERALS]
	},
	MODIFIERS = {
		begin: '[*!#%]',
		relevance: 0
	},
	FUNCTIONS = {
		className: 'function',
		beginKeywords: 'module function',
		end: '\\=|\\{',
		contains: [PARAMS, hljs.UNDERSCORE_TITLE_MODE]
	};

	return {
		aliases: ['scad'],
		keywords: {
			keyword: 'function module include use for intersection_for if else \\%',
			literal: 'false true PI undef',
			built_in: 'circle square polygon text sphere cube cylinder polyhedron translate rotate scale resize mirror multmatrix color offset hull minkowski union difference intersection abs sign sin cos tan acos asin atan atan2 floor round ceil ln log pow sqrt exp rands min max concat lookup str chr search version version_num norm cross parent_module echo import import_dxf dxf_linear_extrude linear_extrude rotate_extrude surface projection render children dxf_cross dxf_dim let assign'
		},
		contains: [
			hljs.C_LINE_COMMENT_MODE,
			hljs.C_BLOCK_COMMENT_MODE,
			NUMBERS,
			PREPRO,
			STRING,
			SPECIAL_VARS,
			MODIFIERS,
			FUNCTIONS
		]
	}
}
);

// #END

// === lang/r.js

/*
Language: R
Author: Joe Cheng <joe@rstudio.org>
Category: scientific
*/

// syntax/lang/r.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('r',
function(hljs) {
	var IDENT_RE = '([a-zA-Z]|\\.[a-zA-Z.])[a-zA-Z0-9._]*';

	return {
		contains: [
			hljs.HASH_COMMENT_MODE,
			{
				begin: IDENT_RE,
				lexemes: IDENT_RE,
				keywords: {
					keyword:
						'function if in break next repeat else for return switch while try tryCatch ' +
						'stop warning require library attach detach source setMethod setGeneric ' +
						'setGroupGeneric setClass ...',
					literal:
						'NULL NA TRUE FALSE T F Inf NaN NA_integer_|10 NA_real_|10 NA_character_|10 ' +
						'NA_complex_|10'
				},
				relevance: 0
			},
			{
				// hex value
				className: 'number',
				begin: "0[xX][0-9a-fA-F]+[Li]?\\b",
				relevance: 0
			},
			{
				// explicit integer
				className: 'number',
				begin: "\\d+(?:[eE][+\\-]?\\d*)?L\\b",
				relevance: 0
			},
			{
				// number with trailing decimal
				className: 'number',
				begin: "\\d+\\.(?!\\d)(?:i\\b)?",
				relevance: 0
			},
			{
				// number
				className: 'number',
				begin: "\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d*)?i?\\b",
				relevance: 0
			},
			{
				// number with leading decimal
				className: 'number',
				begin: "\\.\\d+(?:[eE][+\\-]?\\d*)?i?\\b",
				relevance: 0
			},

			{
				// escaped identifier
				begin: '`',
				end: '`',
				relevance: 0
			},

			{
				className: 'string',
				contains: [hljs.BACKSLASH_ESCAPE],
				variants: [
					{begin: '"', end: '"'},
					{begin: "'", end: "'"}
				]
			}
		]
	};
}
);

// #END

// === lang/scala.js

/*
Language: Scala
Category: functional
Author: Jan Berkel <jan.berkel@gmail.com>
Contributors: Erik Osheim <d_m@plastic-idolatry.com>
*/

// syntax/lang/scala.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('scala',
function(hljs) {

	var ANNOTATION = { className: 'meta', begin: '@[A-Za-z]+' };

	// used in strings for escaping/interpolation/substitution
	var SUBST = {
		className: 'subst',
		variants: [
			{begin: '\\$[A-Za-z0-9_]+'},
			{begin: '\\${', end: '}'}
		]
	};

	var STRING = {
		className: 'string',
		variants: [
			{
				begin: '"', end: '"',
				illegal: '\\n',
				contains: [hljs.BACKSLASH_ESCAPE]
			},
			{
				begin: '"""', end: '"""',
				relevance: 10
			},
			{
				begin: '[a-z]+"', end: '"',
				illegal: '\\n',
				contains: [hljs.BACKSLASH_ESCAPE, SUBST]
			},
			{
				className: 'string',
				begin: '[a-z]+"""', end: '"""',
				contains: [SUBST],
				relevance: 10
			}
		]

	};

	var SYMBOL = {
		className: 'symbol',
		begin: '\'\\w[\\w\\d_]*(?!\')'
	};

	var TYPE = {
		className: 'type',
		begin: '\\b[A-Z][A-Za-z0-9_]*',
		relevance: 0
	};

	var NAME = {
		className: 'title',
		begin: /[^0-9\n\t "'(),.`{}\[\]:;][^\n\t "'(),.`{}\[\]:;]+|[^0-9\n\t "'(),.`{}\[\]:;=]/,
		relevance: 0
	};

	var CLASS = {
		className: 'class',
		beginKeywords: 'class object trait type',
		end: /[:={\[\n;]/,
		excludeEnd: true,
		contains: [
			{
				beginKeywords: 'extends with',
				relevance: 10
			},
			{
				begin: /\[/,
				end: /\]/,
				excludeBegin: true,
				excludeEnd: true,
				relevance: 0,
				contains: [TYPE]
			},
			{
				className: 'params',
				begin: /\(/,
				end: /\)/,
				excludeBegin: true,
				excludeEnd: true,
				relevance: 0,
				contains: [TYPE]
			},
			NAME
		]
	};

	var METHOD = {
		className: 'function',
		beginKeywords: 'def',
		end: /[:={\[(\n;]/,
		excludeEnd: true,
		contains: [NAME]
	};

	return {
		keywords: {
			literal: 'true false null',
			keyword: 'type yield lazy override def with val var sealed abstract private trait object if forSome for while throw finally protected extends import final return else break new catch super class case package default try this match continue throws implicit'
		},
		contains: [
			hljs.C_LINE_COMMENT_MODE,
			hljs.C_BLOCK_COMMENT_MODE,
			STRING,
			SYMBOL,
			TYPE,
			METHOD,
			CLASS,
			hljs.C_NUMBER_MODE,
			ANNOTATION
		]
	};
}
);

// #END

// === lang/swift.js

/*
Language: Swift
Author: Chris Eidhof <chris@eidhof.nl>
Contributors: Nate Cook <natecook@gmail.com>, Alexander Lichter <manniL@gmx.net>
Category: system
*/

// syntax/lang/swift.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('swift',
function(hljs) {
	var SWIFT_KEYWORDS = {
			keyword: '#available #colorLiteral #column #else #elseif #endif #file ' +
				'#fileLiteral #function #if #imageLiteral #line #selector #sourceLocation ' +
				'_ __COLUMN__ __FILE__ __FUNCTION__ __LINE__ Any as as! as? associatedtype ' +
				'associativity break case catch class continue convenience default defer deinit didSet do ' +
				'dynamic dynamicType else enum extension fallthrough false fileprivate final for func ' +
				'get guard if import in indirect infix init inout internal is lazy left let ' +
				'mutating nil none nonmutating open operator optional override postfix precedence ' +
				'prefix private protocol Protocol public repeat required rethrows return ' +
				'right self Self set static struct subscript super switch throw throws true ' +
				'try try! try? Type typealias unowned var weak where while willSet',
			literal: 'true false nil',
			built_in: 'abs advance alignof alignofValue anyGenerator assert assertionFailure ' +
				'bridgeFromObjectiveC bridgeFromObjectiveCUnconditional bridgeToObjectiveC ' +
				'bridgeToObjectiveCUnconditional c contains count countElements countLeadingZeros ' +
				'debugPrint debugPrintln distance dropFirst dropLast dump encodeBitsAsWords ' +
				'enumerate equal fatalError filter find getBridgedObjectiveCType getVaList ' +
				'indices insertionSort isBridgedToObjectiveC isBridgedVerbatimToObjectiveC ' +
				'isUniquelyReferenced isUniquelyReferencedNonObjC join lazy lexicographicalCompare ' +
				'map max maxElement min minElement numericCast overlaps partition posix ' +
				'precondition preconditionFailure print println quickSort readLine reduce reflect ' +
				'reinterpretCast reverse roundUpToAlignment sizeof sizeofValue sort split ' +
				'startsWith stride strideof strideofValue swap toString transcode ' +
				'underestimateCount unsafeAddressOf unsafeBitCast unsafeDowncast unsafeUnwrap ' +
				'unsafeReflect withExtendedLifetime withObjectAtPlusZero withUnsafePointer ' +
				'withUnsafePointerToObject withUnsafeMutablePointer withUnsafeMutablePointers ' +
				'withUnsafePointer withUnsafePointers withVaList zip'
		};

	var TYPE = {
		className: 'type',
		begin: '\\b[A-Z][\\w\u00C0-\u02B8\']*',
		relevance: 0
	};
	var BLOCK_COMMENT = hljs.COMMENT(
		'/\\*',
		'\\*/',
		{
			contains: ['self']
		}
	);
	var SUBST = {
		className: 'subst',
		begin: /\\\(/, end: '\\)',
		keywords: SWIFT_KEYWORDS,
		contains: [] // assigned later
	};
	var STRING = {
		className: 'string',
		contains: [hljs.BACKSLASH_ESCAPE, SUBST],
		variants: [
			{begin: /"""/, end: /"""/},
			{begin: /"/, end: /"/},
		]
	};
	var NUMBERS = {
			className: 'number',
			begin: '\\b([\\d_]+(\\.[\\deE_]+)?|0x[a-fA-F0-9_]+(\\.[a-fA-F0-9p_]+)?|0b[01_]+|0o[0-7_]+)\\b',
			relevance: 0
	};
	SUBST.contains = [NUMBERS];

	return {
		keywords: SWIFT_KEYWORDS,
		contains: [
			STRING,
			hljs.C_LINE_COMMENT_MODE,
			BLOCK_COMMENT,
			TYPE,
			NUMBERS,
			{
				className: 'function',
				beginKeywords: 'func', end: '{', excludeEnd: true,
				contains: [
					hljs.inherit(hljs.TITLE_MODE, {
						begin: /[A-Za-z$_][0-9A-Za-z$_]*/
					}),
					{
						begin: /</, end: />/
					},
					{
						className: 'params',
						begin: /\(/, end: /\)/, endsParent: true,
						keywords: SWIFT_KEYWORDS,
						contains: [
							'self',
							NUMBERS,
							STRING,
							hljs.C_BLOCK_COMMENT_MODE,
							{begin: ':'} // relevance booster
						],
						illegal: /["']/
					}
				],
				illegal: /\[|%/
			},
			{
				className: 'class',
				beginKeywords: 'struct protocol class extension enum',
				keywords: SWIFT_KEYWORDS,
				end: '\\{',
				excludeEnd: true,
				contains: [
					hljs.inherit(hljs.TITLE_MODE, {begin: /[A-Za-z$_][\u00C0-\u02B80-9A-Za-z$_]*/})
				]
			},
			{
				className: 'meta', // @attributes
				begin: '(@discardableResult|@warn_unused_result|@exported|@lazy|@noescape|' +
									'@NSCopying|@NSManaged|@objc|@objcMembers|@convention|@required|' +
									'@noreturn|@IBAction|@IBDesignable|@IBInspectable|@IBOutlet|' +
									'@infix|@prefix|@postfix|@autoclosure|@testable|@available|' +
									'@nonobjc|@NSApplicationMain|@UIApplicationMain)'

			},
			{
				beginKeywords: 'import', end: /$/,
				contains: [hljs.C_LINE_COMMENT_MODE, BLOCK_COMMENT]
			}
		]
	};
}
);

// #END

// ===== [#]

// # JS Package: syntax-lang-ext.pak.js :: #END#

