
// # JS Package: syntax-net-ext.pak.js :: #START# :: @ generated from mod-highlight-syntax/views/js/highlightjs-extra/syntax/net/*.js
// Included Files: net/*.js #

// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###

// === net/ldif.js

/*
Language: LDIF
Contributors: Jacob Childress <jacobc@gmail.com>
Category: enterprise, config
*/

// syntax/net/ldif.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('ldif',
function(hljs) {
	return {
		contains: [
			{
				className: 'attribute',
				begin: '^dn', end: ': ', excludeEnd: true,
				starts: {end: '$', relevance: 0},
				relevance: 10
			},
			{
				className: 'attribute',
				begin: '^\\w', end: ': ', excludeEnd: true,
				starts: {end: '$', relevance: 0}
			},
			{
				className: 'literal',
				begin: '^-', end: '$'
			},
			hljs.HASH_COMMENT_MODE
		]
	};
}
);

// #END

// === net/protobuf.js

/*
Language: Protocol Buffers
Author: Dan Tao <daniel.tao@gmail.com>
Description: Protocol buffer message definition format
Category: protocols
*/

// syntax/net/protobuf.js
// HighlightJs: v.9.13.1

hljs.registerLanguage('protobuf',
function(hljs) {
	return {
		keywords: {
			keyword: 'package import option optional required repeated group oneof',
			built_in: 'double float int32 int64 uint32 uint64 sint32 sint64 ' +
				'fixed32 fixed64 sfixed32 sfixed64 bool string bytes',
			literal: 'true false'
		},
		contains: [
			hljs.QUOTE_STRING_MODE,
			hljs.NUMBER_MODE,
			hljs.C_LINE_COMMENT_MODE,
			{
				className: 'class',
				beginKeywords: 'message enum service', end: /\{/,
				illegal: /\n/,
				contains: [
					hljs.inherit(hljs.TITLE_MODE, {
						starts: {endsWithParent: true, excludeEnd: true} // hack: eating everything after the first title
					})
				]
			},
			{
				className: 'function',
				beginKeywords: 'rpc',
				end: /;/, excludeEnd: true,
				keywords: 'rpc returns'
			},
			{
				begin: /^\s*[A-Z_]+/,
				end: /\s*=/, excludeEnd: true
			}
		]
	};
}
);

// #END

// ===== [#]

// # JS Package: syntax-net-ext.pak.js :: #END#

