#!/bin/sh

# PAK: Multi-Combine all Extra HighlightJs syntax source scripts # r.20210610
# 	from: mod-highlight-syntax/views/js/jshighlight/syntax/*.js
# 	to:   mod-highlight-syntax/views/js/jshighlight/syntax-ext.pak.js

THE_FILE=../mod-highlight-syntax/views/js/jshighlight/syntax-ext.pak.js

echo "Regenerating HighlightJs Syntax Javascript Package: ${THE_FILE}"

echo "" > ${THE_FILE}
echo "// # JS Package: syntax-ext.pak.js :: #START# :: @ generated from mod-highlight-syntax/views/js/jshighlight/syntax/*.js" >> ${THE_FILE}
echo "// Included Files: tpl2/*.js ; lang2/*.js ; ms/*.js ; net2/*.js ; hw/*.js #" >> ${THE_FILE}
echo "" >> ${THE_FILE}
echo "// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###" >> ${THE_FILE}
echo "" >> ${THE_FILE}

#
for SYNTAX_TYPE_SUB in tpl2 lang2 ms net2 hw; do
	echo "Regenerating HighlightJs Syntax[${SYNTAX_TYPE_SUB}] Javascript Package"
	SYNTAX_JS_SUB=`ls -A ../mod-highlight-syntax/views/js/jshighlight/syntax/${SYNTAX_TYPE_SUB}/*.js`
	for i in $SYNTAX_JS_SUB; do
		if [ -f "${i}" ]; then
			#==
			BASE_FILE=`basename "${i}"`
			echo "Javascript: ${SYNTAX_TYPE_SUB}/${BASE_FILE}"
			#==
			echo "// === ${SYNTAX_TYPE_SUB}/${BASE_FILE}" >> ${THE_FILE}
			echo "" >> ${THE_FILE}
			cat ${i} >> ${THE_FILE}
			echo "" >> ${THE_FILE}
			#==
		else
			#==
			echo "FAIL: ${i} is not a file for ${SYNTAX_TYPE_SUB}"
			#==
		fi
	done
	#
done
#

echo "// ===== [#]" >> ${THE_FILE}
echo "" >> ${THE_FILE}
echo "// # JS Package: syntax-ext.pak.js :: #END#" >> ${THE_FILE}
echo "" >> ${THE_FILE}

echo "=== [DONE !] ==="

# END
