#!/bin/sh

# PAK: Multi-Combine all HighlightJs syntax source scripts from mod-highlight-syntax/views/js/highlightjs-extra/syntax/*.js into one package JS file: mod-highlight-syntax/views/js/highlightjs-extra/syntax-ext.pak.js # r.20210326

THE_FILE=../mod-highlight-syntax/views/js/highlightjs-extra/syntax-ext.pak.js

THE_FILE_TPL=../mod-highlight-syntax/views/js/highlightjs-extra/syntax-tpl-ext.pak.js
THE_FILE_LANG=../mod-highlight-syntax/views/js/highlightjs-extra/syntax-lang-ext.pak.js
THE_FILE_MS=../mod-highlight-syntax/views/js/highlightjs-extra/syntax-ms-ext.pak.js
THE_FILE_NET=../mod-highlight-syntax/views/js/highlightjs-extra/syntax-net-ext.pak.js
THE_FILE_HW=../mod-highlight-syntax/views/js/highlightjs-extra/syntax-hw-ext.pak.js


echo "Regenerating HighlightJs Syntax Javascript Package: ${THE_FILE}"

echo "" > ${THE_FILE}
echo "// # JS Package: syntax-ext.pak.js :: #START# :: @ generated from mod-highlight-syntax/views/js/highlightjs-extra/syntax/*.js" >> ${THE_FILE}
echo "// Included Files: tpl/*.js ; lang/*.js ; ms/*.js ; net/*.js ; hw/*.js #" >> ${THE_FILE}
echo "" >> ${THE_FILE}
echo "// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###" >> ${THE_FILE}
echo "" >> ${THE_FILE}


#
SYNTAX_TYPE_SUB=tpl
SYNTAX_FILE_SUB="${THE_FILE_TPL}"
#
echo "Regenerating HighlightJs Syntax[${SYNTAX_TYPE_SUB}] Javascript Package: ${SYNTAX_FILE_SUB}"
echo "" > ${SYNTAX_FILE_SUB}
echo "// # JS Package: syntax-${SYNTAX_TYPE_SUB}-ext.pak.js :: #START# :: @ generated from mod-highlight-syntax/views/js/highlightjs-extra/syntax/${SYNTAX_TYPE_SUB}/*.js" >> ${SYNTAX_FILE_SUB}
echo "// Included Files: ${SYNTAX_TYPE_SUB}/*.js #" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
echo "// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
SYNTAX_JS_SUB=`ls -A ../mod-highlight-syntax/views/js/highlightjs-extra/syntax/${SYNTAX_TYPE_SUB}/*.js`
for i in $SYNTAX_JS_SUB; do
	if [ -f "${i}" ]; then
		#==
		BASE_FILE=`basename "${i}"`
		echo "Javascript: ${SYNTAX_TYPE_SUB}/${BASE_FILE}"
		#==
		echo "// === ${SYNTAX_TYPE_SUB}/${BASE_FILE}" >> ${SYNTAX_FILE_SUB}
		echo "" >> ${SYNTAX_FILE_SUB}
		cat ${i} >> ${SYNTAX_FILE_SUB}
		echo "" >> ${SYNTAX_FILE_SUB}
		#==
		echo "// === ${SYNTAX_TYPE_SUB}/${BASE_FILE}" >> ${THE_FILE}
		echo "" >> ${THE_FILE}
		cat ${i} >> ${THE_FILE}
		echo "" >> ${THE_FILE}
		#==
	else
		#==
		echo "FAIL: ${i} is not a file for ${SYNTAX_TYPE_SUB}"
		#==
	fi
done
echo "// ===== [#]" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
echo "// # JS Package: syntax-${SYNTAX_TYPE_SUB}-ext.pak.js :: #END#" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
#


#
SYNTAX_TYPE_SUB=lang
SYNTAX_FILE_SUB="${THE_FILE_LANG}"
#
echo "Regenerating HighlightJs Syntax[${SYNTAX_TYPE_SUB}] Javascript Package: ${SYNTAX_FILE_SUB}"
echo "" > ${SYNTAX_FILE_SUB}
echo "// # JS Package: syntax-${SYNTAX_TYPE_SUB}-ext.pak.js :: #START# :: @ generated from mod-highlight-syntax/views/js/highlightjs-extra/syntax/${SYNTAX_TYPE_SUB}/*.js" >> ${SYNTAX_FILE_SUB}
echo "// Included Files: ${SYNTAX_TYPE_SUB}/*.js #" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
echo "// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
SYNTAX_JS_SUB=`ls -A ../mod-highlight-syntax/views/js/highlightjs-extra/syntax/${SYNTAX_TYPE_SUB}/*.js`
for i in $SYNTAX_JS_SUB; do
	if [ -f "${i}" ]; then
		#==
		BASE_FILE=`basename "${i}"`
		echo "Javascript: ${SYNTAX_TYPE_SUB}/${BASE_FILE}"
		#==
		echo "// === ${SYNTAX_TYPE_SUB}/${BASE_FILE}" >> ${SYNTAX_FILE_SUB}
		echo "" >> ${SYNTAX_FILE_SUB}
		cat ${i} >> ${SYNTAX_FILE_SUB}
		echo "" >> ${SYNTAX_FILE_SUB}
		#==
		echo "// === ${SYNTAX_TYPE_SUB}/${BASE_FILE}" >> ${THE_FILE}
		echo "" >> ${THE_FILE}
		cat ${i} >> ${THE_FILE}
		echo "" >> ${THE_FILE}
		#==
	else
		#==
		echo "FAIL: ${i} is not a file for ${SYNTAX_TYPE_SUB}"
		#==
	fi
done
echo "// ===== [#]" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
echo "// # JS Package: syntax-${SYNTAX_TYPE_SUB}-ext.pak.js :: #END#" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
#


#
SYNTAX_TYPE_SUB=ms
SYNTAX_FILE_SUB="${THE_FILE_MS}"
#
echo "=== Regenerating HighlightJs Syntax[${SYNTAX_TYPE_SUB}] Javascript Package: ${SYNTAX_FILE_SUB} ==="
echo "" > ${SYNTAX_FILE_SUB}
echo "// # JS Package: syntax-${SYNTAX_TYPE_SUB}-ext.pak.js :: #START# :: @ generated from mod-highlight-syntax/views/js/highlightjs-extra/syntax/${SYNTAX_TYPE_SUB}/*.js" >> ${SYNTAX_FILE_SUB}
echo "// Included Files: ${SYNTAX_TYPE_SUB}/*.js #" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
echo "// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
SYNTAX_JS_SUB=`ls -A ../mod-highlight-syntax/views/js/highlightjs-extra/syntax/${SYNTAX_TYPE_SUB}/*.js`
for i in $SYNTAX_JS_SUB; do
	if [ -f "${i}" ]; then
		#==
		BASE_FILE=`basename "${i}"`
		echo "Javascript: ${SYNTAX_TYPE_SUB}/${BASE_FILE}"
		#==
		echo "// === ${SYNTAX_TYPE_SUB}/${BASE_FILE}" >> ${SYNTAX_FILE_SUB}
		echo "" >> ${SYNTAX_FILE_SUB}
		cat ${i} >> ${SYNTAX_FILE_SUB}
		echo "" >> ${SYNTAX_FILE_SUB}
		#==
		echo "// === ${SYNTAX_TYPE_SUB}/${BASE_FILE}" >> ${THE_FILE}
		echo "" >> ${THE_FILE}
		cat ${i} >> ${THE_FILE}
		echo "" >> ${THE_FILE}
		#==
	else
		#==
		echo "FAIL: ${i} is not a file for ${SYNTAX_TYPE_SUB}"
		#==
	fi
done
echo "// ===== [#]" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
echo "// # JS Package: syntax-${SYNTAX_TYPE_SUB}-ext.pak.js :: #END#" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
#


#
SYNTAX_TYPE_SUB=net
SYNTAX_FILE_SUB="${THE_FILE_NET}"
#
echo "Regenerating HighlightJs Syntax[${SYNTAX_TYPE_SUB}] Javascript Package: ${SYNTAX_FILE_SUB}"
echo "" > ${SYNTAX_FILE_SUB}
echo "// # JS Package: syntax-${SYNTAX_TYPE_SUB}-ext.pak.js :: #START# :: @ generated from mod-highlight-syntax/views/js/highlightjs-extra/syntax/${SYNTAX_TYPE_SUB}/*.js" >> ${SYNTAX_FILE_SUB}
echo "// Included Files: ${SYNTAX_TYPE_SUB}/*.js #" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
echo "// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
SYNTAX_JS_SUB=`ls -A ../mod-highlight-syntax/views/js/highlightjs-extra/syntax/${SYNTAX_TYPE_SUB}/*.js`
for i in $SYNTAX_JS_SUB; do
	if [ -f "${i}" ]; then
		#==
		BASE_FILE=`basename "${i}"`
		echo "Javascript: ${SYNTAX_TYPE_SUB}/${BASE_FILE}"
		#==
		echo "// === ${SYNTAX_TYPE_SUB}/${BASE_FILE}" >> ${SYNTAX_FILE_SUB}
		echo "" >> ${SYNTAX_FILE_SUB}
		cat ${i} >> ${SYNTAX_FILE_SUB}
		echo "" >> ${SYNTAX_FILE_SUB}
		#==
		echo "// === ${SYNTAX_TYPE_SUB}/${BASE_FILE}" >> ${THE_FILE}
		echo "" >> ${THE_FILE}
		cat ${i} >> ${THE_FILE}
		echo "" >> ${THE_FILE}
		#==
	else
		#==
		echo "FAIL: ${i} is not a file for ${SYNTAX_TYPE_SUB}"
		#==
	fi
done
echo "// ===== [#]" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
echo "// # JS Package: syntax-${SYNTAX_TYPE_SUB}-ext.pak.js :: #END#" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
#


#
SYNTAX_TYPE_SUB=hw
SYNTAX_FILE_SUB="${THE_FILE_HW}"
#
echo "Regenerating HighlightJs Syntax[${SYNTAX_TYPE_SUB}] Javascript Package: ${SYNTAX_FILE_SUB}"
echo "" > ${SYNTAX_FILE_SUB}
echo "// # JS Package: syntax-${SYNTAX_TYPE_SUB}-ext.pak.js :: #START# :: @ generated from mod-highlight-syntax/views/js/highlightjs-extra/syntax/${SYNTAX_TYPE_SUB}/*.js" >> ${SYNTAX_FILE_SUB}
echo "// Included Files: ${SYNTAX_TYPE_SUB}/*.js #" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
echo "// ### DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN EACH TIME THE INCLUDED SCRIPTS WILL CHANGE !!! ###" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
SYNTAX_JS_SUB=`ls -A ../mod-highlight-syntax/views/js/highlightjs-extra/syntax/${SYNTAX_TYPE_SUB}/*.js`
for i in $SYNTAX_JS_SUB; do
	if [ -f "${i}" ]; then
		#==
		BASE_FILE=`basename "${i}"`
		echo "Javascript: ${SYNTAX_TYPE_SUB}/${BASE_FILE}"
		#==
		echo "// === ${SYNTAX_TYPE_SUB}/${BASE_FILE}" >> ${SYNTAX_FILE_SUB}
		echo "" >> ${SYNTAX_FILE_SUB}
		cat ${i} >> ${SYNTAX_FILE_SUB}
		echo "" >> ${SYNTAX_FILE_SUB}
		#==
		echo "// === ${SYNTAX_TYPE_SUB}/${BASE_FILE}" >> ${THE_FILE}
		echo "" >> ${THE_FILE}
		cat ${i} >> ${THE_FILE}
		echo "" >> ${THE_FILE}
		#==
	else
		#==
		echo "FAIL: ${i} is not a file for ${SYNTAX_TYPE_SUB}"
		#==
	fi
done
echo "// ===== [#]" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
echo "// # JS Package: syntax-${SYNTAX_TYPE_SUB}-ext.pak.js :: #END#" >> ${SYNTAX_FILE_SUB}
echo "" >> ${SYNTAX_FILE_SUB}
#


echo "// ===== [#]" >> ${THE_FILE}
echo "" >> ${THE_FILE}
echo "// # JS Package: syntax-ext.pak.js :: #END#" >> ${THE_FILE}
echo "" >> ${THE_FILE}

echo "=== [DONE !] ==="

# END
